
import React from 'react';
import { Bot, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { motion } from 'framer-motion';
import InsightCard, { AIInsight } from './InsightCard';

// Sample insights - would be generated by Gemini API in production
const sampleInsights: AIInsight[] = [
  {
    id: '1',
    title: 'Unusual spending detected',
    description: 'Your food expenses are 30% higher than your monthly average.',
    type: 'spending',
    date: new Date()
  },
  {
    id: '2',
    title: 'Smart saving opportunity',
    description: 'Reducing coffee purchases by 2 per week could save you $32 this month.',
    type: 'savings',
    date: new Date()
  },
  {
    id: '3',
    title: 'Spending trend identified',
    description: 'Your travel expenses tend to increase at the end of each quarter.',
    type: 'trend',
    date: new Date()
  }
];

const AIInsightsSection: React.FC = () => {
  return (
    <section>
      <div className="flex justify-between items-center mb-4">
        <div className="flex items-center gap-2">
          <h2 className="text-xl font-semibold">AI Spending Insights</h2>
          <Sparkles className="h-5 w-5 text-primary" />
        </div>
        <Button variant="outline" size="sm" className="text-sm">
          Ask AI Assistant
          <Bot className="ml-2 h-4 w-4" />
        </Button>
      </div>
      
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {sampleInsights.map((insight, index) => (
          <motion.div
            key={insight.id}
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 0.3, delay: index * 0.1 }}
          >
            <InsightCard insight={insight} />
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default AIInsightsSection;
